language: python
sudo: required
dist: xenial
python:
  - "3.7"
env:
  matrix:
    - DJANGO="Django<2"
    - DJANGO="Django<2.1"
    - DJANGO="Django<2.2"
install:
  - pip install -r requirements.txt
matrix:
  exclude:
    - python: "3.7"
      env: DJANGO="Django<2"
branches:
  only:
    - v1.0
before_script:
  - "flake8 ."
script:
  - coverage run --source=drf_multiple_model manage.py test
after_success:
  - coverage report
  - coveralls
